language: ruby
# only run CI-builds on master branch
branches:
  only:
  - master
rvm:
  - 2.4.0
  
before_install: openssl aes-256-cbc -K $encrypted_0c5788daacb5_key -iv $encrypted_0c5788daacb5_iv -in paper-surve-id_rsa.pub.enc -out ~\/.ssh/paper-surve-id_rsa.pub -d
# set execution permission on our build script
before_script:
 - chmod +x ./script/cibuild
# path to our build script. 
# Travis will run `bundle install` by default before running our script
script: ./script/cibuild
exclude: [vendor]
sudo: false

env:
  global:
    - ENCRYPTION_LABEL: 0c5788daacb5
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
      
notifications:
  slack:
    secure: tvhImRwqWN9gX/RADwbUYPoCnvV8hhgxP83RNG4uaTReuvsUyNlGNISjmdIbkFo/KX7nStplb2+NAHCIcwKp6k19ODVpz/F9fUWMKjfSHt3vnOB9OZbo69sjiO9RemCgq11eG1K/oV3useMu9Cgh/gWVIIgat1VZVij8BXLhLx4J49cn+BOvnmDjcg7Tw1EBKG9XBKqar8aobFMP6/gVjtD9zDr5rx9NM/76HxgC6B2bgFSLe5kVabZcaaZapegxzGQd+p2TGvYOjx9UOR4FEZ/+dfz8uTvVCPqmtbtnpym7DHplQrAcKODg4pK5xreInIPMnfv+rxQMENDwQFLPWcig9R/YS1Dobi3v20MDDTQTkcXoq9sLz/2zpclDCY8FhG6C3xhaRCqW6h3eByV6SQq06QEf17X91dmeyMgnq0s1jpPxXVNTFwnFU+fgVckrHqYSWhyTQh10tYg0EePlF7GeJAntci83TJONFUcXuz79w7FkkjBUGo0o0vlSu+ixJIQ9Aeum9qaw2+EFP0PC+58r1bqIkPLrEJJAGOR2MBhvaDeEq8JhEdVg28NWDbqDbmQ/3CY18SH8dXii7NcVU9ivag6buuHXjMEp32+zFtC32QXBCYuxN3D4QIA/c9LsZHb4la/pgketRP0RmkuMuE96+feIRROGihJxLdbx1y8=
