language: ruby
rvm:
- 2.4.0
branches:
  only:
  - master
before_script:
- chmod +x deploy/deploy.sh
script: "./deploy/deploy.sh"
sudo: false
notifications:
  slack:
    secure: hcQcBzqNo7NwySMoHbMIOP3D0brGVa81S3fFF3/MNQfB8X4s2SHBDWyv4UwoUG1Y1RV4Lf2ViHnzPVwJe/QrCrSbNoCvY+ODVIQv4NHPDyK32AByhTLOTY+6KxY82eI8QHaja8QriMMVVeQKXuF7ouMU3ZPUk9FnwqwLE16OeLQ+KVCsf7LMIzZ3J9dJqjfNO5pvOW8SCOgfUwu1/fhoQCFomS9kgrc69cUIlIVLgOL0oC+yLjcj5KLVrgxvZO6TRehfhSFTsQ2PkQd3sI9Ul3PtjAQ1Z4Y5RNyLa1l8FdOIs16hsLawp8UTQe0SCcdYK06rciZhZrr4ZGFtA34Jl9a3EUcuutruSpTq8NbzYdhTCyePqxmGTPa6MMwFD6jxSvXinWZPF/mAAe6NJVK37onhEmgU+PpNzOEJkYPd94v/jJAYiakGD94mHOBHW3KpFbLLKLo6chD7wStY+VzpcHnU2aX5e19g8IjRjVVF8XzCF8IwTsV7dgcq89ouETCgZrz8siOqD/ihEAnBvX62lPWEOmmot1SAorE6b0YMQ1shT6if3cd/PmIlng0yNIZWqZjNPQ8ULMtxxQ4p8d/p50BWTCwYcg0SAwnisTCGCNprNbbjzUQMUAqibEdLkKBe2r4Z15U6XfZLRIrWHfe2GLu9NC4ds7pXbcaiPlnAj9s=
before_install:
- openssl aes-256-cbc -K $encrypted_0c5788daacb5_key -iv $encrypted_0c5788daacb5_iv -in deploy/deploy_paper_survey_key.enc -out /tmp/deploy_key -d
